name: build and deploy to registry

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@main

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        run: |
          docker build . -t ${{ secrets.REGISTRY_SERVER }}/demo-app-api:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_SERVER }}/demo-app-api:${{ github.sha }}
